version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - yum install -y bind-utils
      - yum install -y nginx
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Starting pre-build"

  build:
    commands:
      - echo "Testing DNS resolution and connectivity"
      - zip -r app_build.zip ./*

  post_build:
    commands:
      - echo "Build complete"

artifacts:
  files:
    - '**/*'
  base-directory: .
  name: app_build.zip
  discard-paths: no
  destination: prd-iot-build